# mainline windows build
name: Make CI (MSYS2 for Windows)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # ubuntu-latest = windows-2019
    # https://docs.github.com/ja/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners
    runs-on: windows-latest

    strategy:
      matrix:
        edition:
          - YANEURAOU_ENGINE_NNUE
          - YANEURAOU_ENGINE_NNUE_HALFKPE9
          - YANEURAOU_ENGINE_NNUE_KP256
          - YANEURAOU_ENGINE_KPPT
          - YANEURAOU_ENGINE_KPP_KKPT
          - YANEURAOU_ENGINE_MATERIAL
          - MATE_ENGINE
          - USER_ENGINE
        compiler: [ clang++, g++ ]
        target: [ 'normal,tournament', 'evallearn' ]
        archcpu: [ 'AVX2,SSE42,SSE41,SSSE3,SSE2,ZEN1,ZEN2,NO_SSE', 'ZEN3,AVX512VNNI,AVX512,AVXVNNI,OTHER' ]
        exclude:
          # 以下のエディションには機械学習の実装が存在しない
          # There is no machine learning implementation for the following editions
          - edition: YANEURAOU_ENGINE_MATERIAL
            target: evallearn
          - edition: MATE_ENGINE
            target: evallearn
          - edition: USER_ENGINE
            target: evallearn
          # 自動ビルドチェックから除外
          # Build check exclude: archcpu ZEN3,AVX512VNNI,AVX512,OTHER
          # AVX512VNNI, AVX512, AVXVNNI: NNUE is not yet a code that uses VNNI
          # `-march=cascadelake`: LLVM8, GCC9 support (AVX512VNNI)
          # `-march=alderlake` : LLVM12, GCC11 support (AVX-VNNI)
          # `-march=znver3`: LLVM12 support
          # https://llvm.org/docs/ReleaseNotes.html#changes-to-the-x86-target
          # https://gcc.gnu.org/gcc-11/changes.html#x86
          # https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
          # https://gcc.gnu.org/pipermail/gcc-patches/2020-October/556110.html
          # https://twitter.com/herumi/status/1318418425295720448
          - archcpu: 'ZEN3,AVX512VNNI,AVX512,AVXVNNI,OTHER'

    steps:
    - name: Checkout own repository
      uses: actions/checkout@v2
      with:
        path: main

    - name: Install pkg
      run: |
        C:\msys64\usr\bin\bash.exe -lc 'pacman --needed --noconfirm -Sy pactoys-git'
        C:\msys64\usr\bin\bash.exe -lc 'pacman --needed --noconfirm -Sy pactoys-git'
        C:\msys64\usr\bin\bash.exe -lc 'pacboy --needed --noconfirm -S clang:m openblas:m openmp:m toolchain:m base-devel: msys2-devel:'

    - name: make
      run: |
        $env:PATH+=';C:\msys64';
        .\main\script\msys2_build.ps1 -Edition ${{ matrix.edition }} -Compiler ${{ matrix.compiler }} -Target ${{ matrix.target }} -Cpu ${{ matrix.archcpu }}

    - uses: actions/upload-artifact@v2
      with:
        name: build-windows
        path: ./main/build/**/*
